// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2uZJgiqF-BFEMp_024cjqjYSJx_X82nk',
    appId: '1:749477721461:web:6ab9da1a562b8364d90f3c',
    messagingSenderId: '749477721461',
    projectId: 'foodie-c5e85',
    authDomain: 'foodie-c5e85.firebaseapp.com',
    databaseURL: 'https://foodie-c5e85.firebaseio.com',
    storageBucket: 'foodie-c5e85.appspot.com',
    measurementId: 'G-170WRHGC08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1E8CXh34zqmTYo1BzoQ7O8FJqs0A33-4',
    appId: '1:749477721461:android:b416c0e1d0fb9098d90f3c',
    messagingSenderId: '749477721461',
    projectId: 'foodie-c5e85',
    databaseURL: 'https://foodie-c5e85.firebaseio.com',
    storageBucket: 'foodie-c5e85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWrJ9uIuVCxYjZpZ-3X8EH6s4txkDvLgA',
    appId: '1:749477721461:ios:d32a47b43dc63ee3d90f3c',
    messagingSenderId: '749477721461',
    projectId: 'foodie-c5e85',
    databaseURL: 'https://foodie-c5e85.firebaseio.com',
    storageBucket: 'foodie-c5e85.appspot.com',
    iosClientId: '749477721461-7mcv920t2cou6a6s7l7oc7l2j2krqmfk.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.stackFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWrJ9uIuVCxYjZpZ-3X8EH6s4txkDvLgA',
    appId: '1:749477721461:ios:73d6cd10b46e0549d90f3c',
    messagingSenderId: '749477721461',
    projectId: 'foodie-c5e85',
    databaseURL: 'https://foodie-c5e85.firebaseio.com',
    storageBucket: 'foodie-c5e85.appspot.com',
    iosClientId: '749477721461-ooqn05smg383039oja4bus3mt7361skk.apps.googleusercontent.com',
    iosBundleId: 'com.twentyfirsttech.tatomitho',
  );
}
