// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9iJQeJF6rySE__fciNeW6weSNjeAgb84',
    appId: '1:778059256599:web:86ef27496662fae0635d52',
    messagingSenderId: '778059256599',
    projectId: 'tatomithonotifsystem',
    authDomain: 'tatomithonotifsystem.firebaseapp.com',
    storageBucket: 'tatomithonotifsystem.appspot.com',
    measurementId: 'G-T8WKBFTW82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq62OjV_lcvgh6qposnwhWuecPy4ClwSI',
    appId: '1:778059256599:android:a0df9f51af00bdbd635d52',
    messagingSenderId: '778059256599',
    projectId: 'tatomithonotifsystem',
    storageBucket: 'tatomithonotifsystem.appspot.com',
  );
}
